next-version: 1.0.0
mode: Mainline
branches:
  master:
    regex: (^main$)
    tag: ""
    increment: Patch
    is-release-branch: true
  feature:
    regex: ^feature?[/-]
    tag: useBranchName
    increment: Minor
  bugfix:
    regex: ^hotfix[/-]
    tag: useBranchName
    increment: Patch
    source-branches: ["main"]
